### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow_inference_service'

### ISSUE THREAD

**Issue by dickensons** [tobegit3hub/simple_tensorflow_serving#1]
Hello, sir. First of all, I want to thank you for your attempt to make tensorflow serving friendlier for a regular developer.
After installing simple_tensorflow_serving from your source code I run
 `simple_tensorflow_serving --port=8500 --model_base_path="./examples/tensorflow_template_application_model"`
 and get the following error:
```
$ simple_tensorflow_serving --port=8500 --model_base_path="./examples/tensorflow_template_application_model"
/Users/Dude/anaconda3/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Traceback (most recent call last):
  File "/Users/Dude/anaconda3/bin/simple_tensorflow_serving", line 11, in <module>
    load_entry_point('simple-tensorflow-serving==0.1.2', 'console_scripts', 'simple_tensorflow_serving')()
  File "/Users/Dude/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/Dude/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2769, in load_entry_point
    return ep.load()
  File "/Users/Dude/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2422, in load
    return self.resolve()
  File "/Users/Dude/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2428, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/Dude/anaconda3/lib/python3.6/site-packages/simple_tensorflow_serving-0.1.2-py3.6.egg/simple_tensorflow_serving/server.py", line 10, in <module>
ModuleNotFoundError: No module named 'tensorflow_inference_service'
```
I have a macOS system. I'm sorry if this is a simple question, but I didn't find an answer in the internet. I'm looking forward to using your program for my bachelor project.

**Comment by dickensons** [comment]
I solved it. The problems were with my python environment PATHs.

**Comment by tobegit3hub** [comment]
Great. Thanks for hacking 😃

**Comment by wangzelong0663** [comment]
@dickensons How can you solve it? I also met the same problem.
