### ISSUE TITLE
Docker Run with ImportError: No module named tensorflow_inference_service

### ISSUE THREAD

**Issue by leepengcheng** [tobegit3hub/simple_tensorflow_serving#17]
Traceback (most recent call last):
  File "/usr/local/bin/simple_tensorflow_serving", line 11, in <module>
    load_entry_point('simple-tensorflow-serving==0.4.1', 'console_scripts', 'simple_tensorflow_serving')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/simple_tensorflow_serving-0.4.1-py2.7.egg/simple_tensorflow_serving/server.py", line 20, in <module>
    from tensorflow_inference_service import TensorFlowInferenceService
ImportError: No module named tensorflow_inference_service

**Comment by chiragjn** [comment]
Facing the same issue. PyPI package seems to be broken as well.
Build fails and installs as `unknown-0.0.0`

**Comment by tobegit3hub** [comment]
Thanks have been fixed by https://github.com/tobegit3hub/simple_tensorflow_serving/pull/20 .
