### ISSUE TITLE
dashboard index.html templates not found

### ISSUE THREAD

**Issue by crius79** [tobegit3hub/simple_tensorflow_serving#2]
[2018-03-09 05:44:46,359] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "build/bdist.linux-x86_64/egg/simple_tensorflow_serving/server.py", line 88, in decorated
    return f(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/simple_tensorflow_serving/server.py", line 117, in index
    model_graph_signature=str(inferenceService.model_graph_signature))
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/usr/lib64/python2.7/site-packages/flask/templating.py", line 82, in _get_source_fast
    return loader.get_source(environment, template)
  File "/usr/lib/python2.7/site-packages/jinja2/loaders.py", line 171, in get_source
    f = open_if_exists(filename)
  File "/usr/lib/python2.7/site-packages/jinja2/utils.py", line 154, in open_if_exists
    return open(filename, mode)
IOError: [Errno 20] Not a directory: '/usr/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg/simple_tensorflow_serving/templates/index.html'
INFO:werkzeug:192.168.56.1 - - [09/Mar/2018 05:44:46] "GET / HTTP/1.1" 500 -

**Comment by crius79** [comment]
starts from  python server.py  will be ok .

**Comment by tobegit3hub** [comment]
It would be the problem about packing static file in python package.

Re-open and we should fix it soon.

**Comment by tobegit3hub** [comment]
It is fixed by https://github.com/tobegit3hub/simple_tensorflow_serving/commit/b119ce7e57d3c8e0558a85d094597d4ab276e399 .

You can try with `pip install simple_tensorflow_serving>=0.2.4` now 😃
