### ISSUE TITLE
TemplateNotFound: index.html python2.7

### ISSUE THREAD

**Issue by serlina** [tobegit3hub/simple_tensorflow_serving#61]
Hello, I'm new comer to the simple_tensorflow_serving, and when I'm trying on this follow your structions,  errors happened as below:

—— command:
simple_tensorflow_serving --model_base_path="./models/tensorflow_template_application_model"
—— http://127.0.0.1:8500/  reports 500 error
—— environment:  ubuntu16.04
—— error:
2019-07-23 14:39:07.493490: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2019-07-23 14:39:07.493577: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2019-07-23 14:39:07.493652: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2019-07-23 14:39:07.493725: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2019-07-23 14:39:07.493798: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2019-07-23 14:39:07.493871: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2019-07-23 14:39:07.493948: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcudnn.so.7'; dlerror: libcudnn.so.7: cannot open shared object file: No such file or directory
2019-07-23 14:39:07.493964: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
2019-07-23 14:39:07.493987: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-23 14:39:07.494002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-07-23 14:39:07.494014: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
I0723 14:39:07.494163 139937349682944 tensorflow_inference_service.py:196] Put the model version: 2 online, path: ./models/tensorflow_template_application_model/2
E0723 14:39:08.321846 139937349682944 app.py:1891] Exception on / [GET]
Traceback (most recent call last):
  File "/root/.virtualenvs/tensorflow-env/local/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/.virtualenvs/tensorflow-env/local/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/.virtualenvs/tensorflow-env/local/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/.virtualenvs/tensorflow-env/local/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/.virtualenvs/tensorflow-env/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/.virtualenvs/tensorflow-env/local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./simple_tensorflow_serving/server.py", line 376, in decorated
    return f(*decorator_args, **decorator_kwargs)
  File "./simple_tensorflow_serving/server.py", line 171, in index
    model_name_service_map=self.manager.model_name_service_map)
  File "/root/.virtualenvs/tensorflow-env/local/lib/python2.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/root/.virtualenvs/tensorflow-env/local/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/root/.virtualenvs/tensorflow-env/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/root/.virtualenvs/tensorflow-env/local/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/root/.virtualenvs/tensorflow-env/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/root/.virtualenvs/tensorflow-env/local/lib/python2.7/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/root/.virtualenvs/tensorflow-env/local/lib/python2.7/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: index.html
[pid: 19282|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 690 bytes} [Tue Jul 23 14:39:06 2019] GET / => generated 290 bytes in 1425 msecs (HTTP/1.1 500) 3 headers in 116 bytes (1 switches on core 0)

**Comment by tobegit3hub** [comment]
This has been fix in https://github.com/tobegit3hub/simple_tensorflow_serving/commit/0d9fc7ebd39af09a733f9ed4a765af219ffef6d9 .

You can upgrade to version 0.8.2 by `pip install -U simple-tensorflow-serving>=0.8.2".
