### ISSUE TITLE
tf.GPUOptions bug for Python3.7

### ISSUE THREAD

**Issue by dkawashima** [tobegit3hub/simple_tensorflow_serving#81]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "/usr/local/lib/python3.7/site-packages/simple_tensorflow_serving-0.8.1.1-py3.7.egg/simple_tensorflow_serving/./manager.py", line 89, in init
    self.args.custom_op_paths, session_config)
  File "/usr/local/lib/python3.7/site-packages/simple_tensorflow_serving-0.8.1.1-py3.7.egg/simple_tensorflow_serving/./tensorflow_inference_service.py", line 87, in __init__
    self.load_saved_model_version(model_version)
  File "/usr/local/lib/python3.7/site-packages/simple_tensorflow_serving-0.8.1.1-py3.7.egg/simple_tensorflow_serving/./tensorflow_inference_service.py", line 172, in load_saved_model_version
    gpu_options = tf.GPUOptions(allow_growth=True)
AttributeError: module 'tensorflow' has no attribute 'GPUOptions'

Trying to launch simple-tensorflow-serving as Kubernetes service, and running into issues.

**Comment by ozlerhakan** [comment]
you need to use `tf.compat.v1.GPUOptions(allow_growth=True)` if you run the service with TF 2.0 @dkawashima

**Comment by tobegit3hub** [comment]
It's the issue of compatibility for TF 2 and I will fix for the `tf.compat.v1.GPUOptions(allow_growth=True)` API.

**Comment by tobegit3hub** [comment]
It seems that 0.8.2 has been fixed this.

```
    if tf.__version__.startswith("1"):
      gpu_options = tf.GPUOptions(allow_growth=True)
      config = tf.ConfigProto(gpu_options=gpu_options)
    else:
      gpu_options = tf.compat.v1.GPUOptions(allow_growth=True)
      config = tf.compat.v1.ConfigProto(gpu_options=gpu_options)
```

Please upgrade to test by `pip install -U simple_tensorflow_serving>=0.8.2".
